# Generated by Django 5.1.6 on 2026-06-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_addded',
            new_name='date_added',
        ),
    ]
